import { Catalog, Product, Size } from './types';

// ── Placeholder imagery ─────────────────────────────────────────
// High-resolution Unsplash photos (free to use). Every image slot
// also has a styled fallback (see components/Img.tsx) so nothing
// ever renders blank, even if a remote photo is removed.

const U = (id: string, w = 1400) =>
  `https://images.unsplash.com/photo-${id}?q=85&w=${w}&auto=format&fit=crop`;

const stock = (xs: number, s: number, m: number, l: number, xl: number): Record<Size, number> => ({
  XS: xs, S: s, M: m, L: l, XL: xl,
});

const now = new Date().toISOString();

export const seedCatalog: Catalog = {
  categories: [
    {
      id: 'cat-new',
      name: 'New Arrivals',
      slug: 'new-arrivals',
      imageUrl: U('1507525428034-b723cf961d3e'),
      sortOrder: 1,
      isActive: true,
    },
    {
      id: 'cat-best',
      name: 'Best Sellers',
      slug: 'best-sellers',
      imageUrl: U('1519046904884-53103b34b206'),
      sortOrder: 2,
      isActive: true,
    },
    {
      id: 'cat-bikinis',
      name: 'Bikinis',
      slug: 'bikinis',
      imageUrl: U('1505118380757-91f5f5632de0'),
      sortOrder: 3,
      isActive: true,
    },
    {
      id: 'cat-swim',
      name: 'Swimwear',
      slug: 'swimwear',
      imageUrl: U('1510414842594-a61c69b5ae57'),
      sortOrder: 4,
      isActive: true,
    },
  ],

  products: [
    {
      id: 'p-01',
      slug: 'ama-mango-sorbet',
      name: 'AMA — MANGO SORBET',
      colorName: 'Mango Sorbet',
      colorHex: '#F5A25D',
      priceGhs: 380,
      description:
        'A sun-drenched triangle set in our signature ribbed fabric. Sliding cups let you fine-tune coverage, while tie sides on the bottom adjust to your exact fit. Made for long afternoons at Labadi and lazy pool days.',
      fabric: 'Ribbed nylon-spandex blend. Fully lined. Quick-dry.',
      fit: 'Triangle top with sliding cups. Tie-side bottom, cheeky coverage.',
      care: 'Hand wash cold. Dry flat in shade. Do not tumble dry.',
      categoryIds: ['cat-new', 'cat-bikinis', 'cat-swim'],
      images: [U('1544966503-7cc5ac882d5f'), U('1520520731457-9283dd14aa66')],
      topStock: stock(6, 10, 10, 8, 4),
      bottomStock: stock(6, 10, 10, 8, 4),
      isActive: true,
      isFeatured: true,
      createdAt: now,
    },
    {
      id: 'p-02',
      slug: 'efia-midnight',
      name: 'EFIA — MIDNIGHT',
      colorName: 'Midnight Black',
      colorHex: '#101820',
      priceGhs: 420,
      description:
        'The one you will reach for every time. A deep black halter set with gold-tone hardware and a sculpting underband. Timeless, flattering, and built to outlast every season.',
      fabric: 'Matte Italian lycra. Double lined for opacity.',
      fit: 'Halter-neck top with removable padding. Mid-rise classic bottom.',
      care: 'Rinse after swimming. Hand wash cold. Dry flat.',
      categoryIds: ['cat-best', 'cat-bikinis', 'cat-swim'],
      images: [U('1519046904884-53103b34b206'), U('1476673160081-cf065607f449')],
      topStock: stock(5, 12, 12, 9, 5),
      bottomStock: stock(5, 12, 12, 9, 5),
      isActive: true,
      isFeatured: true,
      createdAt: now,
    },
    {
      id: 'p-03',
      slug: 'serwaa-hibiscus',
      name: 'SERWAA — HIBISCUS',
      colorName: 'Hibiscus Pink',
      colorHex: '#E64980',
      priceGhs: 350,
      description:
        'Bold hibiscus pink in a scoop-neck crop silhouette. Wide underband stays put through swims and beach volleyball alike. A statement without trying.',
      fabric: 'Recycled nylon blend with four-way stretch.',
      fit: 'Scoop crop top, medium support. High-cut bottom.',
      care: 'Hand wash cold with mild soap. Avoid rough surfaces.',
      categoryIds: ['cat-new', 'cat-bikinis'],
      images: [U('1505118380757-91f5f5632de0'), U('1523471826770-c437b4636fe6')],
      topStock: stock(4, 8, 9, 7, 3),
      bottomStock: stock(4, 8, 9, 7, 3),
      isActive: true,
      isFeatured: true,
      createdAt: now,
    },
    {
      id: 'p-04',
      slug: 'akosua-seafoam',
      name: 'AKOSUA — SEAFOAM',
      colorName: 'Seafoam Green',
      colorHex: '#8FD5C6',
      priceGhs: 320,
      description:
        'Soft seafoam green with delicate ring details at the hips and bust. Light, minimal, and easy — the set you pack first.',
      fabric: 'Smooth microfibre lycra. UPF 50+.',
      fit: 'Bralette top with adjustable straps. Ring-side bottom.',
      care: 'Hand wash cold. Do not bleach. Dry away from direct sun.',
      categoryIds: ['cat-bikinis', 'cat-swim'],
      images: [U('1510414842594-a61c69b5ae57'), U('1473116763249-2faaef81ccda')],
      topStock: stock(6, 9, 9, 6, 3),
      bottomStock: stock(6, 9, 9, 6, 3),
      isActive: true,
      isFeatured: false,
      createdAt: now,
    },
    {
      id: 'p-05',
      slug: 'abena-cocoa',
      name: 'ABENA — COCOA',
      colorName: 'Cocoa Brown',
      colorHex: '#6B4A38',
      priceGhs: 390,
      description:
        'Rich cocoa brown that flatters every skin tone. A balconette shape with structured cups gives real support without wires digging in.',
      fabric: 'Textured crinkle fabric, fully lined.',
      fit: 'Balconette top, firm support. Mid-coverage bottom.',
      care: 'Hand wash cold. Reshape while damp. Dry flat.',
      categoryIds: ['cat-best', 'cat-bikinis'],
      images: [U('1520520731457-9283dd14aa66'), U('1544966503-7cc5ac882d5f')],
      topStock: stock(5, 10, 11, 8, 4),
      bottomStock: stock(5, 10, 11, 8, 4),
      isActive: true,
      isFeatured: true,
      createdAt: now,
    },
    {
      id: 'p-06',
      slug: 'adjoa-tangerine',
      name: 'ADJOA — TANGERINE',
      colorName: 'Tangerine',
      colorHex: '#F0552D',
      priceGhs: 340,
      description:
        'Electric tangerine in a clean triangle cut. The colour of a Cape Coast sunset — impossible to miss, impossible not to love.',
      fabric: 'High-gloss lycra with a subtle sheen.',
      fit: 'Classic triangle top. Tie-side cheeky bottom.',
      care: 'Rinse in fresh water after use. Hand wash cold.',
      categoryIds: ['cat-new', 'cat-bikinis'],
      images: [U('1476673160081-cf065607f449'), U('1507525428034-b723cf961d3e')],
      topStock: stock(4, 9, 9, 7, 3),
      bottomStock: stock(4, 9, 9, 7, 3),
      isActive: true,
      isFeatured: false,
      createdAt: now,
    },
    {
      id: 'p-07',
      slug: 'yaa-lagoon',
      name: 'YAA — LAGOON',
      colorName: 'Lagoon Blue',
      colorHex: '#2C6E8F',
      priceGhs: 360,
      description:
        'Deep lagoon blue with contrast white piping. Sporty enough to actually swim in, sleek enough for the beach club.',
      fabric: 'Chlorine-resistant performance knit.',
      fit: 'Sport crop top. Full-coverage bottom.',
      care: 'Machine wash cold in a garment bag, or hand wash.',
      categoryIds: ['cat-swim', 'cat-bikinis'],
      images: [U('1473116763249-2faaef81ccda'), U('1510414842594-a61c69b5ae57')],
      topStock: stock(5, 8, 10, 8, 5),
      bottomStock: stock(5, 8, 10, 8, 5),
      isActive: true,
      isFeatured: false,
      createdAt: now,
    },
    {
      id: 'p-08',
      slug: 'esi-vanilla',
      name: 'ESI — VANILLA',
      colorName: 'Vanilla Cream',
      colorHex: '#F2E8D5',
      priceGhs: 300,
      description:
        'Warm vanilla cream in a barely-there silhouette. Gold-tone sliders and a soft ribbed texture make this the quiet luxury pick of the collection.',
      fabric: 'Fine-rib knit, double lined so it never turns sheer.',
      fit: 'Micro triangle top. Low-rise tie bottom.',
      care: 'Hand wash cold separately. Dry flat in shade.',
      categoryIds: ['cat-bikinis'],
      images: [U('1523471826770-c437b4636fe6'), U('1505118380757-91f5f5632de0')],
      topStock: stock(6, 10, 8, 6, 2),
      bottomStock: stock(6, 10, 8, 6, 2),
      isActive: true,
      isFeatured: false,
      createdAt: now,
    },
    {
      id: 'p-09',
      slug: 'afia-palm',
      name: 'AFIA — PALM',
      colorName: 'Palm Green',
      colorHex: '#2E5B3E',
      priceGhs: 370,
      description:
        'Deep palm green inspired by the Aburi hills. A twist-front top adds shape and interest, with a matching high-waist bottom that smooths and holds.',
      fabric: 'Sculpting compression lycra.',
      fit: 'Twist-front bandeau. High-waist bottom, full coverage.',
      care: 'Hand wash cold. Do not wring. Dry flat.',
      categoryIds: ['cat-best', 'cat-swim'],
      images: [U('1507525428034-b723cf961d3e'), U('1519046904884-53103b34b206')],
      topStock: stock(4, 8, 9, 8, 4),
      bottomStock: stock(4, 8, 9, 8, 4),
      isActive: true,
      isFeatured: false,
      createdAt: now,
    },
    {
      id: 'p-10',
      slug: 'maame-berry',
      name: 'MAAME — BERRY',
      colorName: 'Berry Crush',
      colorHex: '#8E2D56',
      priceGhs: 410,
      description:
        'Crushed-velvet berry with a plunge neckline and adjustable back tie. Rich texture, deep colour, maximum drama.',
      fabric: 'Stretch velvet with swim-grade lining.',
      fit: 'Plunge halter top. Cheeky velvet bottom.',
      care: 'Hand wash cold, inside out. Never iron velvet.',
      categoryIds: ['cat-new', 'cat-best', 'cat-bikinis'],
      images: [U('1520520731457-9283dd14aa66'), U('1476673160081-cf065607f449')],
      topStock: stock(3, 7, 8, 6, 3),
      bottomStock: stock(3, 7, 8, 6, 3),
      isActive: true,
      isFeatured: true,
      createdAt: now,
    },
    {
      id: 'p-11',
      slug: 'akua-shoreline',
      name: 'AKUA — SHORELINE',
      colorName: 'Shoreline Stripe',
      colorHex: '#4A7FA5',
      priceGhs: 330,
      description:
        'Breton-inspired blue and white stripes in a square-neck crop. Clean, nautical, and endlessly photogenic against the sand.',
      fabric: 'Yarn-dyed stripe knit, colourfast in salt water.',
      fit: 'Square-neck crop top. Mid-rise classic bottom.',
      care: 'Hand wash cold. Wash with similar colours.',
      categoryIds: ['cat-bikinis', 'cat-swim'],
      images: [U('1473116763249-2faaef81ccda'), U('1523471826770-c437b4636fe6')],
      topStock: stock(5, 9, 9, 7, 4),
      bottomStock: stock(5, 9, 9, 7, 4),
      isActive: true,
      isFeatured: false,
      createdAt: now,
    },
    {
      id: 'p-12',
      slug: 'ohemaa-gold-dust',
      name: 'OHEMAA — GOLD DUST',
      colorName: 'Gold Dust',
      colorHex: '#C9A24B',
      priceGhs: 450,
      description:
        'Our crown piece. Shimmering gold-dust fabric that catches light with every move, cut in a refined triangle silhouette. Fit for an Ohemaa.',
      fabric: 'Metallic shimmer lycra, fully lined.',
      fit: 'Fixed triangle top with back tie. Tie-side bottom.',
      care: 'Hand wash cold gently. Dry flat. Handle with care.',
      categoryIds: ['cat-new', 'cat-best', 'cat-bikinis'],
      images: [U('1544966503-7cc5ac882d5f'), U('1510414842594-a61c69b5ae57')],
      topStock: stock(3, 6, 7, 5, 2),
      bottomStock: stock(3, 6, 7, 5, 2),
      isActive: true,
      isFeatured: true,
      createdAt: now,
    },
  ],
};
